### ISSUE TITLE
Listar Jogadores

### ISSUE THREAD

**Issue by bernardohrl** [Gambot-Crupier/Gambot-App#1]
## História de Usuário

Eu, como usuário, desejo visualizar uma lista com os jogadores que vão participar do jogo.
 

## Descrição
Após fazer o login, os usuários devem ser redirecionados à uma página que apresenta a lista de jogadores que desejam participar do jogo. Após clicar em 'Iniciar Jogo', os usuários serão levado à etapa de calibragem.

## Tasks
* [ ] Adicionar atributo 'gameState' que pode ter 3 estados: 'starting', 'in progress', 'finished'.
* [ ] Os usuários, após o login, devem ser redirecionádos à pagina de Entrar no jogo.
* [ ] Os usuários, após clicar em entrar no jogo, devem ser redirecionados à página Listar Players.
* [ ] Os players que clicaram para entrar no jogo devem ser apresentados em uma lista que se atualiza.
* [ ] Os usuários podem escolher sair do jogo.
