### ISSUE TITLE
Iniciar Jogo

### ISSUE THREAD

**Issue by bernardohrl** [Gambot-Crupier/Gambot-App#2]
## História de Usuário

Eu, como usuário, desejo iniciar um jogo quando todos os jogadores estiverem prontos.
 

## Descrição
Após todos os usuários estarem listados, algum dos usuários poderá clicar para iniciar um jogo.

## Tasks
* [ ] No mínimo 2 usuários devem estar na lista do jogo para que ele possa ser iniciado.
* [ ] O usuário deve clicar em um botão para iniciar a partida.
* [ ] Todos os usuários são levados para a tela inicial do jogo.
