### ISSUE TITLE
Maior Sequência

### ISSUE THREAD

**Issue by bernardohrl** [Gambot-Crupier/Gambot-App#3]
## História de Usuário

Eu, como usuário, desejo saber qual a maior sequência na rodada.
 

## Descrição
Após receber as cartas, as sequências dos usuários devem ser registradas.

## Tasks
* [ ] Deve ser registrado uma sequência de acordo com as cartas da mão e da mesa de cada player.
* [ ] A prioridade de cada sequência deve ser registrada, ordenando de 1 a QTD_PLAYERS.
* [ ] Apresentar, no aplicativo, qual usuário possui a maior sequência.
